export const PUNCH_IN_REQUEST = 'PUNCH_IN_REQUEST';
export const PUNCH_IN_SUCCESS = 'PUNCH_IN_SUCCESS';
export const PUNCH_IN_FAILURE = 'PUNCH_IN_FAILURE';

export const PUNCH_OUT_REQUEST = 'PUNCH_OUT_REQUEST';
export const PUNCH_OUT_SUCCESS = 'PUNCH_OUT_SUCCESS';
export const PUNCH_OUT_FAILURE = 'PUNCH_OUT_FAILURE';

export const FETCH_MY_ATTENDANCE_REQUEST = 'FETCH_MY_ATTENDANCE_REQUEST';
export const FETCH_MY_ATTENDANCE_SUCCESS = 'FETCH_MY_ATTENDANCE_SUCCESS';
export const FETCH_MY_ATTENDANCE_FAILURE = 'FETCH_MY_ATTENDANCE_FAILURE';

export const FETCH_TEAM_ATTENDANCE_REQUEST = 'FETCH_TEAM_ATTENDANCE_REQUEST';
export const FETCH_TEAM_ATTENDANCE_SUCCESS = 'FETCH_TEAM_ATTENDANCE_SUCCESS';
export const FETCH_TEAM_ATTENDANCE_FAILURE = 'FETCH_TEAM_ATTENDANCE_FAILURE';

export const LOCATION_CHECK_IN_REQUEST = 'LOCATION_CHECK_IN_REQUEST';
export const LOCATION_CHECK_IN_SUCCESS = 'LOCATION_CHECK_IN_SUCCESS';
export const LOCATION_CHECK_IN_FAILURE = 'LOCATION_CHECK_IN_FAILURE';

export const LOCATION_CHECK_OUT_REQUEST = 'LOCATION_CHECK_OUT_REQUEST';
export const LOCATION_CHECK_OUT_SUCCESS = 'LOCATION_CHECK_OUT_SUCCESS';
export const LOCATION_CHECK_OUT_FAILURE = 'LOCATION_CHECK_OUT_FAILURE';

export const FETCH_MY_VISITS_REQUEST = 'FETCH_MY_VISITS_REQUEST';
export const FETCH_MY_VISITS_SUCCESS = 'FETCH_MY_VISITS_SUCCESS';
export const FETCH_MY_VISITS_FAILURE = 'FETCH_MY_VISITS_FAILURE';

export const FETCH_TEAM_VISITS_REQUEST = 'FETCH_TEAM_VISITS_REQUEST';
export const FETCH_TEAM_VISITS_SUCCESS = 'FETCH_TEAM_VISITS_SUCCESS';
export const FETCH_TEAM_VISITS_FAILURE = 'FETCH_TEAM_VISITS_FAILURE';
