export const COMPANY_ACTIVE_DEATIVE_BUTTON_REQUEST_SUCCESS = "COMPANY_ACTIVE_DEATIVE_BUTTON_REQUEST_SUCCESS";
export const COMPANY_ACTIVE_DEATIVE_BUTTON_REQUEST_FAILURE = "COMPANY_ACTIVE_DEATIVE_BUTTON_REQUEST_FAILURE";
export const COMPANY_ACTIVE_DEATIVE_BUTTON_REQUEST_REQUEST = "COMPANY_ACTIVE_DEATIVE_BUTTON_REQUEST_REQUEST";

export const COMPANY_EDIT_DATA_REQUEST_SUCCESS = "COMPANY_EDIT_DATA_REQUEST_SUCCESS";
export const COMPANY_EDIT_DATA_REQUEST_FAILURE = "COMPANY_EDIT_DATA_REQUEST_FAILURE";
export const COMPANY_EDIT_DATA_REQUEST_REQUEST = "COMPANY_EDIT_DATA_REQUEST_REQUEST";

export const COMPANY_OFFER_LETTER_GENERATE_SUCCESS = 'COMPANY_OFFER_LETTER_GENERATE_SUCCESS';
export const COMPANY_OFFER_LETTER_GENERATE_FAILURE = 'COMPANY_OFFER_LETTER_GENERATE_FAILURE';
export const COMPANY_OFFER_LETTER_GENERATE_REQUEST = 'COMPANY_OFFER_LETTER_GENERATE_REQUEST';

export const COMPANY_RELEIVING_LETTER_GENERATE_SUCCESS = 'COMPANY_RELEIVING_LETTER_GENERATE_SUCCESS';
export const COMPANY_RELEIVING_LETTER_GENERATE_FAILURE = 'COMPANY_RELEIVING_LETTER_GENERATE_FAILURE';
export const COMPANY_RELEIVING_LETTER_GENERATE_REQUEST = 'COMPANY_RELEIVING_LETTER_GENERATE_REQUEST';

export const COMPANY_PAYSLIP_GENERATE_SUCCESS = 'COMPANY_PAYSLIP_GENERATE_SUCCESS';
export const COMPANY_PAYSLIP_GENERATE_FAILURE = 'COMPANY_PAYSLIP_GENERATE_FAILURE';
export const COMPANY_PAYSLIP_GENERATE_REQUEST = 'COMPANY_PAYSLIP_GENERATE_REQUEST';

export const COMPANY_GET_ROLES_REQUEST = 'COMPANY_GET_ROLES_REQUEST';
export const COMPANY_GET_ROLES_SUCCESS = 'COMPANY_GET_ROLES_SUCCESS';
export const COMPANY_GET_ROLES_FAILURE = 'COMPANY_GET_ROLES_FAILURE';

export const COMPANY_GET_DEPARTMENTS_REQUEST = 'COMPANY_GET_DEPARTMENTS_REQUEST';
export const COMPANY_GET_DEPARTMENTS_SUCCESS = 'COMPANY_GET_DEPARTMENTS_SUCCESS';
export const COMPANY_GET_DEPARTMENTS_FAILURE = 'COMPANY_GET_DEPARTMENTS_FAILURE';