export const FETCH_MY_DCRS_REQUEST = 'FETCH_MY_DCRS_REQUEST';
export const FETCH_MY_DCRS_SUCCESS = 'FETCH_MY_DCRS_SUCCESS';
export const FETCH_MY_DCRS_FAILURE = 'FETCH_MY_DCRS_FAILURE';

export const SAVE_DCR_DRAFT_REQUEST = 'SAVE_DCR_DRAFT_REQUEST';
export const SAVE_DCR_DRAFT_SUCCESS = 'SAVE_DCR_DRAFT_SUCCESS';
export const SAVE_DCR_DRAFT_FAILURE = 'SAVE_DCR_DRAFT_FAILURE';

export const SUBMIT_DCR_REQUEST = 'SUBMIT_DCR_REQUEST';
export const SUBMIT_DCR_SUCCESS = 'SUBMIT_DCR_SUCCESS';
export const SUBMIT_DCR_FAILURE = 'SUBMIT_DCR_FAILURE';

export const FETCH_DCR_DETAILS_REQUEST = 'FETCH_DCR_DETAILS_REQUEST';
export const FETCH_DCR_DETAILS_SUCCESS = 'FETCH_DCR_DETAILS_SUCCESS';
export const FETCH_DCR_DETAILS_FAILURE = 'FETCH_DCR_DETAILS_FAILURE';

export const CLEAR_DCR_ERRORS = 'CLEAR_DCR_ERRORS';
export const CLEAR_DCR_SUCCESS = 'CLEAR_DCR_SUCCESS';

export const FETCH_TEAM_DCRS_REQUEST = 'FETCH_TEAM_DCRS_REQUEST';
export const FETCH_TEAM_DCRS_SUCCESS = 'FETCH_TEAM_DCRS_SUCCESS';
export const FETCH_TEAM_DCRS_FAILURE = 'FETCH_TEAM_DCRS_FAILURE';

export const REVIEW_DCR_REQUEST = 'REVIEW_DCR_REQUEST';
export const REVIEW_DCR_SUCCESS = 'REVIEW_DCR_SUCCESS';
export const REVIEW_DCR_FAILURE = 'REVIEW_DCR_FAILURE';
