export const FETCH_PAYSLIP_REQUEST = 'FETCH_PAYSLIP_REQUEST';
export const FETCH_PAYSLIP_SUCCESS = 'FETCH_PAYSLIP_SUCCESS';
export const FETCH_PAYSLIP_FAILURE = 'FETCH_PAYSLIP_FAILURE';

export const FETCH_LATEST_PAYSLIP_REQUEST = 'FETCH_LATEST_PAYSLIP_REQUEST';
export const FETCH_LATEST_PAYSLIP_SUCCESS = 'FETCH_LATEST_PAYSLIP_SUCCESS';
export const FETCH_LATEST_PAYSLIP_FAILURE = 'FETCH_LATEST_PAYSLIP_FAILURE';

export const FETCH_RELIEVING_LETTER_REQUEST = 'FETCH_RELIEVING_LETTER_REQUEST';
export const FETCH_RELIEVING_LETTER_SUCCESS = 'FETCH_RELIEVING_LETTER_SUCCESS';
export const FETCH_RELIEVING_LETTER_FAILURE = 'FETCH_RELIEVING_LETTER_FAILURE';

export const FETCH_TERMINATION_LETTER_REQUEST = 'FETCH_TERMINATION_LETTER_REQUEST';
export const FETCH_TERMINATION_LETTER_SUCCESS = 'FETCH_TERMINATION_LETTER_SUCCESS';
export const FETCH_TERMINATION_LETTER_FAILURE = 'FETCH_TERMINATION_LETTER_FAILURE';

export const CLEAR_DOCUMENT_ERRORS = 'CLEAR_DOCUMENT_ERRORS';
