export const FETCH_HOLIDAYS_REQUEST = 'FETCH_HOLIDAYS_REQUEST';
export const FETCH_HOLIDAYS_SUCCESS = 'FETCH_HOLIDAYS_SUCCESS';
export const FETCH_HOLIDAYS_FAILURE = 'FETCH_HOLIDAYS_FAILURE';

export const FETCH_UPCOMING_HOLIDAYS_REQUEST = 'FETCH_UPCOMING_HOLIDAYS_REQUEST';
export const FETCH_UPCOMING_HOLIDAYS_SUCCESS = 'FETCH_UPCOMING_HOLIDAYS_SUCCESS';
export const FETCH_UPCOMING_HOLIDAYS_FAILURE = 'FETCH_UPCOMING_HOLIDAYS_FAILURE';

export const FETCH_ACTIVE_UPCOMING_HOLIDAYS_REQUEST = 'FETCH_ACTIVE_UPCOMING_HOLIDAYS_REQUEST';
export const FETCH_ACTIVE_UPCOMING_HOLIDAYS_SUCCESS = 'FETCH_ACTIVE_UPCOMING_HOLIDAYS_SUCCESS';
export const FETCH_ACTIVE_UPCOMING_HOLIDAYS_FAILURE = 'FETCH_ACTIVE_UPCOMING_HOLIDAYS_FAILURE';

export const SYNC_HOLIDAYS_REQUEST = 'SYNC_HOLIDAYS_REQUEST';
export const SYNC_HOLIDAYS_SUCCESS = 'SYNC_HOLIDAYS_SUCCESS';
export const SYNC_HOLIDAYS_FAILURE = 'SYNC_HOLIDAYS_FAILURE';

export const CREATE_HOLIDAY_REQUEST = 'CREATE_HOLIDAY_REQUEST';
export const CREATE_HOLIDAY_SUCCESS = 'CREATE_HOLIDAY_SUCCESS';
export const CREATE_HOLIDAY_FAILURE = 'CREATE_HOLIDAY_FAILURE';

export const UPDATE_HOLIDAY_REQUEST = 'UPDATE_HOLIDAY_REQUEST';
export const UPDATE_HOLIDAY_SUCCESS = 'UPDATE_HOLIDAY_SUCCESS';
export const UPDATE_HOLIDAY_FAILURE = 'UPDATE_HOLIDAY_FAILURE';

export const DELETE_HOLIDAY_REQUEST = 'DELETE_HOLIDAY_REQUEST';
export const DELETE_HOLIDAY_SUCCESS = 'DELETE_HOLIDAY_SUCCESS';
export const DELETE_HOLIDAY_FAILURE = 'DELETE_HOLIDAY_FAILURE';

export const TOGGLE_HOLIDAY_VISIBILITY_REQUEST = 'TOGGLE_HOLIDAY_VISIBILITY_REQUEST';
export const TOGGLE_HOLIDAY_VISIBILITY_SUCCESS = 'TOGGLE_HOLIDAY_VISIBILITY_SUCCESS';
export const TOGGLE_HOLIDAY_VISIBILITY_FAILURE = 'TOGGLE_HOLIDAY_VISIBILITY_FAILURE';

export const CLEAR_HOLIDAY_ERRORS = 'CLEAR_HOLIDAY_ERRORS';
export const CLEAR_HOLIDAY_SUCCESS = 'CLEAR_HOLIDAY_SUCCESS';
