export const FETCH_MY_LEAVES_REQUEST = 'FETCH_MY_LEAVES_REQUEST';
export const FETCH_MY_LEAVES_SUCCESS = 'FETCH_MY_LEAVES_SUCCESS';
export const FETCH_MY_LEAVES_FAILURE = 'FETCH_MY_LEAVES_FAILURE';

export const APPLY_LEAVE_REQUEST = 'APPLY_LEAVE_REQUEST';
export const APPLY_LEAVE_SUCCESS = 'APPLY_LEAVE_SUCCESS';
export const APPLY_LEAVE_FAILURE = 'APPLY_LEAVE_FAILURE';

export const FETCH_TEAM_LEAVES_REQUEST = 'FETCH_TEAM_LEAVES_REQUEST';
export const FETCH_TEAM_LEAVES_SUCCESS = 'FETCH_TEAM_LEAVES_SUCCESS';
export const FETCH_TEAM_LEAVES_FAILURE = 'FETCH_TEAM_LEAVES_FAILURE';

export const REVIEW_LEAVE_REQUEST = 'REVIEW_LEAVE_REQUEST';
export const REVIEW_LEAVE_SUCCESS = 'REVIEW_LEAVE_SUCCESS';
export const REVIEW_LEAVE_FAILURE = 'REVIEW_LEAVE_FAILURE';

export const CLEAR_LEAVE_ERRORS = 'CLEAR_LEAVE_ERRORS';
export const CLEAR_LEAVE_SUCCESS = 'CLEAR_LEAVE_SUCCESS';
