export const FETCH_MY_LEAVES_REQUEST = 'FETCH_MY_LEAVES_REQUEST';
export const FETCH_MY_LEAVES_SUCCESS = 'FETCH_MY_LEAVES_SUCCESS';
export const FETCH_MY_LEAVES_FAILURE = 'FETCH_MY_LEAVES_FAILURE';

export const APPLY_LEAVE_REQUEST = 'APPLY_LEAVE_REQUEST';
export const APPLY_LEAVE_SUCCESS = 'APPLY_LEAVE_SUCCESS';
export const APPLY_LEAVE_FAILURE = 'APPLY_LEAVE_FAILURE';

export const FETCH_TEAM_LEAVES_REQUEST = 'FETCH_TEAM_LEAVES_REQUEST';
export const FETCH_TEAM_LEAVES_SUCCESS = 'FETCH_TEAM_LEAVES_SUCCESS';
export const FETCH_TEAM_LEAVES_FAILURE = 'FETCH_TEAM_LEAVES_FAILURE';

export const REVIEW_LEAVE_REQUEST = 'REVIEW_LEAVE_REQUEST';
export const REVIEW_LEAVE_SUCCESS = 'REVIEW_LEAVE_SUCCESS';
export const REVIEW_LEAVE_FAILURE = 'REVIEW_LEAVE_FAILURE';

// Leave Types CRUD
export const FETCH_LEAVE_TYPES_REQUEST = 'FETCH_LEAVE_TYPES_REQUEST';
export const FETCH_LEAVE_TYPES_SUCCESS = 'FETCH_LEAVE_TYPES_SUCCESS';
export const FETCH_LEAVE_TYPES_FAILURE = 'FETCH_LEAVE_TYPES_FAILURE';

export const CREATE_LEAVE_TYPE_REQUEST = 'CREATE_LEAVE_TYPE_REQUEST';
export const CREATE_LEAVE_TYPE_SUCCESS = 'CREATE_LEAVE_TYPE_SUCCESS';
export const CREATE_LEAVE_TYPE_FAILURE = 'CREATE_LEAVE_TYPE_FAILURE';

export const UPDATE_LEAVE_TYPE_REQUEST = 'UPDATE_LEAVE_TYPE_REQUEST';
export const UPDATE_LEAVE_TYPE_SUCCESS = 'UPDATE_LEAVE_TYPE_SUCCESS';
export const UPDATE_LEAVE_TYPE_FAILURE = 'UPDATE_LEAVE_TYPE_FAILURE';

export const DELETE_LEAVE_TYPE_REQUEST = 'DELETE_LEAVE_TYPE_REQUEST';
export const DELETE_LEAVE_TYPE_SUCCESS = 'DELETE_LEAVE_TYPE_SUCCESS';
export const DELETE_LEAVE_TYPE_FAILURE = 'DELETE_LEAVE_TYPE_FAILURE';

// Leave Balances
export const FETCH_MY_BALANCES_REQUEST = 'FETCH_MY_BALANCES_REQUEST';
export const FETCH_MY_BALANCES_SUCCESS = 'FETCH_MY_BALANCES_SUCCESS';
export const FETCH_MY_BALANCES_FAILURE = 'FETCH_MY_BALANCES_FAILURE';

export const FETCH_EMPLOYEE_BALANCES_REQUEST = 'FETCH_EMPLOYEE_BALANCES_REQUEST';
export const FETCH_EMPLOYEE_BALANCES_SUCCESS = 'FETCH_EMPLOYEE_BALANCES_SUCCESS';
export const FETCH_EMPLOYEE_BALANCES_FAILURE = 'FETCH_EMPLOYEE_BALANCES_FAILURE';

export const FETCH_ADMIN_BALANCE_SUMMARY_REQUEST = 'FETCH_ADMIN_BALANCE_SUMMARY_REQUEST';
export const FETCH_ADMIN_BALANCE_SUMMARY_SUCCESS = 'FETCH_ADMIN_BALANCE_SUMMARY_SUCCESS';
export const FETCH_ADMIN_BALANCE_SUMMARY_FAILURE = 'FETCH_ADMIN_BALANCE_SUMMARY_FAILURE';

export const FETCH_ADMIN_THIS_MONTH_SUMMARY_REQUEST = 'FETCH_ADMIN_THIS_MONTH_SUMMARY_REQUEST';
export const FETCH_ADMIN_THIS_MONTH_SUMMARY_SUCCESS = 'FETCH_ADMIN_THIS_MONTH_SUMMARY_SUCCESS';
export const FETCH_ADMIN_THIS_MONTH_SUMMARY_FAILURE = 'FETCH_ADMIN_THIS_MONTH_SUMMARY_FAILURE';

// Admin Leave Requests
export const FETCH_ADMIN_LEAVES_TABLE_REQUEST = 'FETCH_ADMIN_LEAVES_TABLE_REQUEST';
export const FETCH_ADMIN_LEAVES_TABLE_SUCCESS = 'FETCH_ADMIN_LEAVES_TABLE_SUCCESS';
export const FETCH_ADMIN_LEAVES_TABLE_FAILURE = 'FETCH_ADMIN_LEAVES_TABLE_FAILURE';

export const FETCH_ADMIN_LEAVES_SUMMARY_REQUEST = 'FETCH_ADMIN_LEAVES_SUMMARY_REQUEST';
export const FETCH_ADMIN_LEAVES_SUMMARY_SUCCESS = 'FETCH_ADMIN_LEAVES_SUMMARY_SUCCESS';
export const FETCH_ADMIN_LEAVES_SUMMARY_FAILURE = 'FETCH_ADMIN_LEAVES_SUMMARY_FAILURE';

export const CLEAR_LEAVE_ERRORS = 'CLEAR_LEAVE_ERRORS';
export const CLEAR_LEAVE_SUCCESS = 'CLEAR_LEAVE_SUCCESS';
