export const FETCH_NOTIFICATIONS_REQUEST = 'FETCH_NOTIFICATIONS_REQUEST';
export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS';
export const FETCH_NOTIFICATIONS_FAILURE = 'FETCH_NOTIFICATIONS_FAILURE';

export const FETCH_UNREAD_NOTIFICATIONS_REQUEST = 'FETCH_UNREAD_NOTIFICATIONS_REQUEST';
export const FETCH_UNREAD_NOTIFICATIONS_SUCCESS = 'FETCH_UNREAD_NOTIFICATIONS_SUCCESS';
export const FETCH_UNREAD_NOTIFICATIONS_FAILURE = 'FETCH_UNREAD_NOTIFICATIONS_FAILURE';

export const FETCH_UNREAD_COUNT_REQUEST = 'FETCH_UNREAD_COUNT_REQUEST';
export const FETCH_UNREAD_COUNT_SUCCESS = 'FETCH_UNREAD_COUNT_SUCCESS';
export const FETCH_UNREAD_COUNT_FAILURE = 'FETCH_UNREAD_COUNT_FAILURE';

export const MARK_NOTIFICATION_READ_REQUEST = 'MARK_NOTIFICATION_READ_REQUEST';
export const MARK_NOTIFICATION_READ_SUCCESS = 'MARK_NOTIFICATION_READ_SUCCESS';
export const MARK_NOTIFICATION_READ_FAILURE = 'MARK_NOTIFICATION_READ_FAILURE';

export const MARK_ALL_READ_REQUEST = 'MARK_ALL_READ_REQUEST';
export const MARK_ALL_READ_SUCCESS = 'MARK_ALL_READ_SUCCESS';
export const MARK_ALL_READ_FAILURE = 'MARK_ALL_READ_FAILURE';

export const DELETE_NOTIFICATION_REQUEST = 'DELETE_NOTIFICATION_REQUEST';
export const DELETE_NOTIFICATION_SUCCESS = 'DELETE_NOTIFICATION_SUCCESS';
export const DELETE_NOTIFICATION_FAILURE = 'DELETE_NOTIFICATION_FAILURE';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const CLEAR_SUCCESS = 'CLEAR_SUCCESS';
