export const GET_NOTICES_REQUEST = 'GET_NOTICES_REQUEST';
export const GET_NOTICES_SUCCESS = 'GET_NOTICES_SUCCESS';
export const GET_NOTICES_FAILURE = 'GET_NOTICES_FAILURE';

export const GET_ACTIVE_NOTICES_REQUEST = 'GET_ACTIVE_NOTICES_REQUEST';
export const GET_ACTIVE_NOTICES_SUCCESS = 'GET_ACTIVE_NOTICES_SUCCESS';
export const GET_ACTIVE_NOTICES_FAILURE = 'GET_ACTIVE_NOTICES_FAILURE';

export const CREATE_NOTICE_REQUEST = 'CREATE_NOTICE_REQUEST';
export const CREATE_NOTICE_SUCCESS = 'CREATE_NOTICE_SUCCESS';
export const CREATE_NOTICE_FAILURE = 'CREATE_NOTICE_FAILURE';

export const UPDATE_NOTICE_REQUEST = 'UPDATE_NOTICE_REQUEST';
export const UPDATE_NOTICE_SUCCESS = 'UPDATE_NOTICE_SUCCESS';
export const UPDATE_NOTICE_FAILURE = 'UPDATE_NOTICE_FAILURE';

export const TOGGLE_ACTIVE_NOTICE_REQUEST = 'TOGGLE_ACTIVE_NOTICE_REQUEST';
export const TOGGLE_ACTIVE_NOTICE_SUCCESS = 'TOGGLE_ACTIVE_NOTICE_SUCCESS';
export const TOGGLE_ACTIVE_NOTICE_FAILURE = 'TOGGLE_ACTIVE_NOTICE_FAILURE';

export const DELETE_NOTICE_REQUEST = 'DELETE_NOTICE_REQUEST';
export const DELETE_NOTICE_SUCCESS = 'DELETE_NOTICE_SUCCESS';
export const DELETE_NOTICE_FAILURE = 'DELETE_NOTICE_FAILURE';

export const CLEAR_NOTICE_ERRORS = 'CLEAR_NOTICE_ERRORS';
export const CLEAR_NOTICE_SUCCESS = 'CLEAR_NOTICE_SUCCESS';
