export const GET_VISIT_SUMMARY_REQUEST = 'GET_VISIT_SUMMARY_REQUEST';
export const GET_VISIT_SUMMARY_SUCCESS = 'GET_VISIT_SUMMARY_SUCCESS';
export const GET_VISIT_SUMMARY_FAILURE = 'GET_VISIT_SUMMARY_FAILURE';

export const GET_DATEWISE_DAILY_REQUEST = 'GET_DATEWISE_DAILY_REQUEST';
export const GET_DATEWISE_DAILY_SUCCESS = 'GET_DATEWISE_DAILY_SUCCESS';
export const GET_DATEWISE_DAILY_FAILURE = 'GET_DATEWISE_DAILY_FAILURE';

export const GET_CALL_VISIT_REQUEST = 'GET_CALL_VISIT_REQUEST';
export const GET_CALL_VISIT_SUCCESS = 'GET_CALL_VISIT_SUCCESS';
export const GET_CALL_VISIT_FAILURE = 'GET_CALL_VISIT_FAILURE';

export const GET_DCR_DAY_REQUEST = 'GET_DCR_DAY_REQUEST';
export const GET_DCR_DAY_SUCCESS = 'GET_DCR_DAY_SUCCESS';
export const GET_DCR_DAY_FAILURE = 'GET_DCR_DAY_FAILURE';

export const GET_DAILY_ACTIVITY_REQUEST = 'GET_DAILY_ACTIVITY_REQUEST';
export const GET_DAILY_ACTIVITY_SUCCESS = 'GET_DAILY_ACTIVITY_SUCCESS';
export const GET_DAILY_ACTIVITY_FAILURE = 'GET_DAILY_ACTIVITY_FAILURE';

export const GET_WEEKLY_CROSS_REQUEST = 'GET_WEEKLY_CROSS_REQUEST';
export const GET_WEEKLY_CROSS_SUCCESS = 'GET_WEEKLY_CROSS_SUCCESS';
export const GET_WEEKLY_CROSS_FAILURE = 'GET_WEEKLY_CROSS_FAILURE';

export const CLEAR_REPORT_ERRORS = 'CLEAR_REPORT_ERRORS';

export const DISTRIBUTES_REPORT_REQUEST = 'DISTRIBUTES_REPORT_REQUEST';
export const DISTRIBUTES_REPORT_SUCCESS = 'DISTRIBUTES_REPORT_SUCCESS';
export const DISTRIBUTES_REPORT_FAILURE = 'DISTRIBUTES_REPORT_FAILURE';

export const GET_DISTRIBUTORS_REQUEST = 'GET_DISTRIBUTORS_REQUEST';
export const GET_DISTRIBUTORS_SUCCESS = 'GET_DISTRIBUTORS_SUCCESS';
export const GET_DISTRIBUTORS_FAILURE = 'GET_DISTRIBUTORS_FAILURE';