export const FETCH_PENDING_REQUESTS_REQUEST = 'FETCH_PENDING_REQUESTS_REQUEST';
export const FETCH_PENDING_REQUESTS_SUCCESS = 'FETCH_PENDING_REQUESTS_SUCCESS';
export const FETCH_PENDING_REQUESTS_FAILURE = 'FETCH_PENDING_REQUESTS_FAILURE';

export const FETCH_ME_REQUESTS_REQUEST = 'FETCH_ME_REQUESTS_REQUEST';
export const FETCH_ME_REQUESTS_SUCCESS = 'FETCH_ME_REQUESTS_SUCCESS';
export const FETCH_ME_REQUESTS_FAILURE = 'FETCH_ME_REQUESTS_FAILURE';

export const SUBMIT_ONBOARDING_REQUEST_REQUEST = 'SUBMIT_ONBOARDING_REQUEST_REQUEST';
export const SUBMIT_ONBOARDING_REQUEST_SUCCESS = 'SUBMIT_ONBOARDING_REQUEST_SUCCESS';
export const SUBMIT_ONBOARDING_REQUEST_FAILURE = 'SUBMIT_ONBOARDING_REQUEST_FAILURE';

export const REVIEW_ONBOARDING_REQUEST_REQUEST = 'REVIEW_ONBOARDING_REQUEST_REQUEST';
export const REVIEW_ONBOARDING_REQUEST_SUCCESS = 'REVIEW_ONBOARDING_REQUEST_SUCCESS';
export const REVIEW_ONBOARDING_REQUEST_FAILURE = 'REVIEW_ONBOARDING_REQUEST_FAILURE';

export const UPDATE_DOCTOR_LOCATION_REQUEST = 'UPDATE_DOCTOR_LOCATION_REQUEST';
export const UPDATE_DOCTOR_LOCATION_SUCCESS = 'UPDATE_DOCTOR_LOCATION_SUCCESS';
export const UPDATE_DOCTOR_LOCATION_FAILURE = 'UPDATE_DOCTOR_LOCATION_FAILURE';
