export const UPDATE_ADMIN_SETTINGS_SUCCESS = 'UPDATE_ADMIN_SETTINGS_SUCCESS';
export const UPDATE_ADMIN_SETTINGS_FAILURE = 'UPDATE_ADMIN_SETTINGS_FAILURE';
export const UPDATE_ADMIN_SETTINGS_REQUEST = 'UPDATE_ADMIN_SETTINGS_REQUEST';


