export const TEAM_LIST_REQUEST = 'TEAM_LIST_REQUEST';
export const TEAM_LIST_SUCCESS = 'TEAM_LIST_SUCCESS';
export const TEAM_LIST_FAILURE = 'TEAM_LIST_FAILURE';

export const TEAM_ONBOARD_REQUEST = 'TEAM_ONBOARD_REQUEST';
export const TEAM_ONBOARD_SUCCESS = 'TEAM_ONBOARD_SUCCESS';
export const TEAM_ONBOARD_FAILURE = 'TEAM_ONBOARD_FAILURE';

export const DOCTOR_EXCEL_UPLOAD_REQUEST = 'DOCTOR_EXCEL_UPLOAD_REQUEST';
export const DOCTOR_EXCEL_UPLOAD_SUCCESS = 'DOCTOR_EXCEL_UPLOAD_SUCCESS';
export const DOCTOR_EXCEL_UPLOAD_FAILURE = 'DOCTOR_EXCEL_UPLOAD_FAILURE';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const CLEAR_SUCCESS = 'CLEAR_SUCCESS';
