export const FETCH_MY_TOUR_PLANS_REQUEST = 'FETCH_MY_TOUR_PLANS_REQUEST';
export const FETCH_MY_TOUR_PLANS_SUCCESS = 'FETCH_MY_TOUR_PLANS_SUCCESS';
export const FETCH_MY_TOUR_PLANS_FAILURE = 'FETCH_MY_TOUR_PLANS_FAILURE';

export const SAVE_TOUR_PLAN_DRAFT_REQUEST = 'SAVE_TOUR_PLAN_DRAFT_REQUEST';
export const SAVE_TOUR_PLAN_DRAFT_SUCCESS = 'SAVE_TOUR_PLAN_DRAFT_SUCCESS';
export const SAVE_TOUR_PLAN_DRAFT_FAILURE = 'SAVE_TOUR_PLAN_DRAFT_FAILURE';

export const SUBMIT_TOUR_PLAN_REQUEST = 'SUBMIT_TOUR_PLAN_REQUEST';
export const SUBMIT_TOUR_PLAN_SUCCESS = 'SUBMIT_TOUR_PLAN_SUCCESS';
export const SUBMIT_TOUR_PLAN_FAILURE = 'SUBMIT_TOUR_PLAN_FAILURE';

export const FETCH_TOUR_PLAN_DETAILS_REQUEST = 'FETCH_TOUR_PLAN_DETAILS_REQUEST';
export const FETCH_TOUR_PLAN_DETAILS_SUCCESS = 'FETCH_TOUR_PLAN_DETAILS_SUCCESS';
export const FETCH_TOUR_PLAN_DETAILS_FAILURE = 'FETCH_TOUR_PLAN_DETAILS_FAILURE';

export const FETCH_TEAM_TOUR_PLANS_REQUEST = 'FETCH_TEAM_TOUR_PLANS_REQUEST';
export const FETCH_TEAM_TOUR_PLANS_SUCCESS = 'FETCH_TEAM_TOUR_PLANS_SUCCESS';
export const FETCH_TEAM_TOUR_PLANS_FAILURE = 'FETCH_TEAM_TOUR_PLANS_FAILURE';

export const REVIEW_TOUR_PLAN_REQUEST = 'REVIEW_TOUR_PLAN_REQUEST';
export const REVIEW_TOUR_PLAN_SUCCESS = 'REVIEW_TOUR_PLAN_SUCCESS';
export const REVIEW_TOUR_PLAN_FAILURE = 'REVIEW_TOUR_PLAN_FAILURE';

export const CLEAR_TOUR_PLAN_ERRORS = 'CLEAR_TOUR_PLAN_ERRORS';
export const CLEAR_TOUR_PLAN_SUCCESS = 'CLEAR_TOUR_PLAN_SUCCESS';
